[project]
name = "flaskr"
version = "0.1.0"
description = ""
authors = [
    {name = "denizugurgenc02",email = "denizugurgenc02@hotmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask (>=3.1.2,<4.0.0)",
    "python-dotenv (>=1.2.1,<2.0.0)",
    "flask-sqlalchemy (>=3.1.1,<4.0.0)",
    "psycopg2-binary (>=2.9.11,<3.0.0)",
    "flask-migrate (>=4.1.0,<5.0.0)",
    "injector (>=0.23.0,<0.24.0)",
    "pre-commit (>=4.5.1,<5.0.0)",
    "marshmallow (>=4.3.0,<5.0.0)"
]


[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
