"""change the user.password model

Revision ID: e238e98ececc
Revises: e8e0a57376d0
Create Date: 2026-04-11 04:10:19.347766

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e238e98ececc"
down_revision = "e8e0a57376d0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "password",
            existing_type=sa.VARCHAR(length=128),
            type_=sa.String(length=512),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "password",
            existing_type=sa.String(length=512),
            type_=sa.VARCHAR(length=128),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
